### ISSUE TITLE
关于案例32_ESP8266_Rtos3.0_NVSWiFi中的问题

### ISSUE THREAD

**Issue by LiThirteen** [xuhongv/StudyInEsp8266#14]
在ESP8266_Rtos(esp-idf风格)中，关于wifi：esp_wifi_set_storage(wifi_storage_t storage ); 这样的api可以将wifi的配置信息写入到nvs中，同时也能上电自动连接，为何还需自定义命名空间来存储wifi的信息呢，请问您这样做的想法是什么呢？

**Comment by xuhongv** [comment]
- 这个代码出来时候，是没有 esp_wifi_set_storage(wifi_storage_t storage ); 方法的。现在出来的话，那就更好了；
