### ISSUE TITLE
FreeRTOS 3.0+版本 实现wifi+串口透传功能咨询

### ISSUE THREAD

**Issue by ScienceZhi** [xuhongv/StudyInEsp8266#15]
在CSDN上看到了博主的文章，加群后看到来git上提问有利于后人观看，便来了。
打算做一个wifi配合串口的透传功能，即，8266 RX0收到的数据通过8266的socket发出去， socket收到的数据通过TX0发送出去。
考虑到程序设计的可靠性，而非粗暴搭建来实现功能等因素，想问问博主，目前已发布的例程中，有没有跟我需求相似

**Comment by xuhongv** [comment]
这个很简单呐 如果你没别的需求，可以直接拿 AT固件实现即可
