### ISSUE TITLE
关于固件烧写的问题

### ISSUE THREAD

**Issue by luofengBJ** [xuhongv/StudyInEsp8266#2]
你好，看了博主的教程进行尝试，发现nonosV2.1的sdk，smart_config的example中user_main.c里面已经没有init_done_cb()了，只有user_init()，我就直接在user_init里面添加了。
编译出来的固件，两个文件，地址一个是0x0,另一个是0x10000，与教程的0x40000是不一样的，烧进去后也显示csum err，后来直接试了你这里面smart_config里面的bin文件，按照0x0和0x40000的地址直接烧进去，也是显示csumerr。想请教下，是哪里设置出现错误了吗？

**Comment by xuhongv** [comment]
- 烧录地址是0x40000，您使用的应该是旧版的SDK把。现在的版本 1.4开始都是 0x1000了！PS:不好意思，现在才看到！
