### ISSUE TITLE
不知道徐工有没有遇到过烧录固件时一直卡在等待上电同步

### ISSUE THREAD

**Issue by YuriChen1028** [xuhongv/StudyInEsp8266#4]
确认烧录设置没有出错，之前板子多次烧录都没问题，不知道哪天开始烧录都卡在等待上电同步，没法烧录程序了。之前波特率设置都是115200。

**Comment by xuhongv** [comment]
- 这种问题是 板子没有进去烧录模式， 注意 GPIO0为低电平、gpio15为高电平、gpio2为高电平！
- 看设备上电后的74880的日志最好，对应的模式对比下就可以了！这个和烧录的波特率设置没关系的！
