### ISSUE TITLE
烧录问题

### ISSUE THREAD

**Issue by Jiangwei0802** [xuhongv/StudyInEsp8266#6]
才接触esp8266,用的模组是ESP-WROOM-02D，烧录工具上读出的信息flash是16Mbit,我按照esp8266_quick_start_guide_cn指导，用官方环境编译，NONOS_SDK/at例程，设置：
![image](https://user-images.githubusercontent.com/9602379/54804203-99820900-4cad-11e9-8e2d-d4ecae4287fd.png)
也能正常产生bin文件，烧录文件设置：
![image](https://user-images.githubusercontent.com/9602379/54804271-c6362080-4cad-11e9-9c79-aea1e9ee34b7.png)
烧录后发现模块没有正常跑起来，
![image](https://user-images.githubusercontent.com/9602379/54804304-efef4780-4cad-11e9-9fb8-791a05a4c51b.png)
是哪里的愿因呢？

**Comment by xuhongv** [comment]
- 烧录错了
